// Generated by Visual Studio's Code_in.
// Generated by Visual Studio's Code_in.
// Generated by Visual Studio's Code_in.
// Generated by Visual Studio's Code_in.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public sealed class Program
{
	public static void Main ()
	{
		Console.WriteLine ("HelloWorld");
		if (System.Diagnostics.Debugger.IsAttached)
			System.Diagnostics.Debugger.Break ();
		Console.Read ();
	}
}
