using code_in.Presenters.Nodal;
using ICSharpCode.NRefactory.CSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace code_in.Models.NodalModel
{
    public class DeclarationsNodalModel : INodalModel
    {
        public bool IsSaved
        {
            get;
            set;
        }
        public DeclarationsNodalPresenterLocal Presenter;
        public SyntaxTree AST
        {
            get;
            private set;
        }
        public string FilePath
        {
            get;
            private set;
        }
        public string FileName
        {
            get
            {
                return Path.GetFileName(FilePath);
            }
        }

        public DeclarationsNodalModel(string filePath)
        {

            FilePath = filePath;
            try
            {
                AST = _parseFile(FilePath);
            }
            catch (Exception e)
            {
                // TODO
                //Presenter.Close();
                MessageBox.Show(e.ToString());
            }
        }

        private SyntaxTree _parseFile(string filePath)
        {
            var parser = new ICSharpCode.NRefactory.CSharp.CSharpParser();
            StreamReader fileStream = new StreamReader(filePath);
            SyntaxTree ast = parser.Parse(fileStream);
            fileStream.Close();
            return ast;
        }


        public void Save()
        {
            string saveExtension = Path.GetExtension(FilePath);
            System.Windows.MessageBox.Show(Path.GetFileNameWithoutExtension(FilePath) + ".cdn" + saveExtension, "Save file path");
            //using (System.IO.StreamWriter sw = new System.IO.StreamWriter(Path.GetFileNameWithoutExtension(FilePath) + ".cdn" + saveExtension))
            //{
            //    String code = "// Generated by Visual Studio's Code_in.";
            //    sw.AutoFlush = true;
            //    sw.WriteLine(code);
            //    sw.Write(AST.ToString());
            //    sw.Close();
            //}
        }
    }
}
