using code_in.Models;
using code_in.Models.NodalModel;
using code_in.Views.NodalView;
using ICSharpCode.NRefactory.CSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace code_in.Presenters.Nodal
{
    public class NodalPresenter : INodalPresenter
    {
        public NodalPresenter(NodalView view)
        {
            _view = view;
            _parser = new CSharpParser();

        }

        NodalView   _view; // TODO INodalView
        NodalModel  _model = null;
        CSharpParser _parser = null;

        public void OpenFile(String path)
        {
            _model = this.ParseFile(path);
            _view.GenerateVisualNodes(_model);
        }

        public NodalModel ParseFile(String path)
        {
            StreamReader fileStream = new StreamReader(path);
            var ast = _parser.Parse(fileStream);
            NodalModel model = new NodalModel(ast);
            return model;
        }

        public void SaveFile(String filePath)
        {
            System.IO.StreamWriter sw = new System.IO.StreamWriter(filePath);
            String code = "// Generated by Visual Studio's Code_in.";
            sw.WriteLine(code);
            //sw.Write(_codeData.AST.ToString());
        }
    }
}